### PR TITLE
Change logic that checks if all threads are done. Future is much more appropriate for this purpose.

### PR DESCRIPTION
**Pull request by victorlaerte**

### CODE REVIEW

**Comment by mimno** [comment]
This looks great, thank you!

It looks like it might be a good idea to convert WorkerRunnable to Callable to better handle exceptions. What do you think?

**Comment by victorlaerte** [comment]
@mimno sure. I'll take a deeper look into this, I didn't know if you still merging pull requests. But if so I'll improve this.

**Comment by mimno** [comment]
I don't have much time to review them. This is a priority, though.

**Comment by victorlaerte** [comment]
@mimno I've seen you already implemented all the improvements for this PR. Great job. Thanks.

**Pull request closed without merging**
