### PR TITLE
Pipe test bug fix 

### PR DESCRIPTION
**Pull request by clairew**
@mimno @linbojin

Fixed bug introduced in this merge - https://github.com/mimno/Mallet/pull/120 

Please review asap, thanks!

### CODE REVIEW

**Comment by linbojin** [comment]
There is another one: https://github.com/mimno/Mallet/blob/master/src/cc/mallet/pipe/tests/TestTokenSequence2PorterStems.java#L170

**Comment by clairew** [comment]
@linbojin did you get these mistakes by building with maven?

**Comment by linbojin** [comment]
Yes...

**Comment by clairew** [comment]
@linbojin Ok please be patient with me! Also feel free to open a PR to fix the bugs.

**Pull request merged**
