### PR TITLE
Pipe test refactor

### PR DESCRIPTION
**Pull request by clairew**
Quick refactor of pipe tests - removing wildcard imports and unused imports

### CODE REVIEW

**Comment by clairew** [comment]
@mimno

**Comment by linbojin** [comment]
This pr introduced minor bug in TestCharSequenceNoDiacritics.java: 
Line List<Pipe> pipes = new ArrayList<>();
ArrayList is not found.

**Comment by clairew** [comment]
@linbojin  Thanks for pointing this out - fixing this now.

**Comment by linbojin** [comment]
@clairew do you build Mallet by maven?

**Pull request merged**
