### PR TITLE
Add support for numeric features in GRMM

### PR DESCRIPTION
**Pull request by nrockweiler**
- Code changes were outlined in this mailing list conversation:
http://t47962.ai-mallet-development.aitalk.info/continuous-observations-for-dcrf-t47962.html.
 - Special thanks to Ming Tu.

### CODE REVIEW

**Comment by casutton** [comment]
Dear Nicole, Ming, 

Thanks very much for this! This has probably been the #1 most common question about GRMM, so I'm really glad to see this patch.

I only had one question about this, which was the handling of offset conjunctions? Right now, it looks like if you have a line with features like

   XYZZY=1.5 XYZZY=0.25@-1

Then the "-1" will be ignored and the "XYZZY" feature will be set twice. Am I reading the code right, or were you expecting offset features to be expressed in a different way?

Charles

**Comment by nrockweiler** [comment]
I've tried digging into the code, but I'm still a little confused how GRMM handles features with offsets.  Do features with offsets have special meaning, or are they treated as just another feature, i.e., the offset is just to make the input data easier to read for the user?

Currently, the patch assumes the latter.  In your example, two features would be created.  The first feature would have the key "XYZZY=1.5" and a value of 1.5 and the second feature would have the key "XYZZY=0.25@-1" and a value of 0.25.  If this assumption is incorrect, let me know and I can update the patch.

On a similar note, can you briefly explain if GRMM gives special meaning to features like \<START1\>@-3 and XXX_&_YYY?

Thank you.
Nicole

Oh, and receiving this comment from one of the CRF gods made my day!

**Comment by casutton** [comment]
On 24 Jun 2015, at 19:01, Nicole Rockweiler wrote:

> I've tried digging into the code, but I'm still a little confused how 
> GRMM handles features with offsets.  Do features with offsets have 
> special meaning, or are they treated as just another feature, i.e., 
> the offset is just to make the input data easier to read for the user?

They are treated just as any other feature.

> Currently, the patch assumes the latter.  In your example, two 
> features would be created.  The first feature would have the key 
> "XYZZY=1.5" and a value of 1.5 and the second feature would have the 
> key "XYZZY=0.25@-1" and a value of 0.25.

Ah, I see. Thanks for the clarification. I had misread the patch; I 
incorrectly thought that you were creating two features named 
“XYZZY”. Sorry about that.

I think that the behaviour that you describe is probably best.
The other alternative would be to have two features

	name: XYZZY value 1.5
	name: XYZZY@-1 value 0.25

That’s a little bit prettier, but I think your current way is maybe a 
bit more transparent
to the user, so I think that your current way is probably better.

I will go ahead and merge this patch now. Thanks very much for your 
contribution!

> On a similar note, can you briefly explain if GRMM gives special 
> meaning to features like \<START1\>@-3 and XXX_&_YYY?

GRMM does absolutely no interpretation of feature names, so
<START1>@-3 and XXX_&_YYY are currently treated just like any other 
binary features.

Best wishes
Charles

-- 
Charles Sutton * csutton@inf.ed.ac.uk * 
http://homepages.inf.ed.ac.uk/csutton
Reader * School of Informatics * University of Edinburgh
Deputy Director, EPSRC CDT in Data Science * 
http://datascience.inf.ed.ac.uk/

Please excuse brevity: http://theoatmeal.com/comics/email_monster

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by nrockweiler** [comment]
Thanks for the detailed explanation!


-Nicole

**Pull request merged**
